{
    "name": "EcoSphere: ESG Management",
    "version": "17.0.1.0.0",
    "category": "Human Resources",
    "summary": "Environmental, Social, Governance & Gamification platform",
    "depends": ["base", "mail", "hr", "purchase", "hr_expense", "fleet",
                "base_automation", "product"],
    "data": [
        "security/ecosphere_esg_security.xml",
        "security/ir.model.access.csv",
        "data/esg_emission_factor_data.xml",
        "data/esg_automation_data.xml",
        "data/esg_cron_data.xml",
        "views/esg_menus.xml",
        "views/esg_department_views.xml",
        "views/esg_category_views.xml",
        "views/esg_emission_factor_views.xml",
        "views/esg_product_profile_views.xml",
        "views/esg_environmental_goal_views.xml",
        "views/esg_carbon_transaction_views.xml",
        "views/esg_csr_activity_views.xml",
        "views/esg_employee_participation_views.xml",
        "views/esg_policy_views.xml",
        "views/esg_audit_views.xml",
        "views/esg_compliance_issue_views.xml",
        "views/hr_employee_views.xml",
        "views/res_config_settings_views.xml",
    ],
    "demo": [],
    "assets": {
        "web.assets_backend": [
            "ecosphere_esg/static/src/scss/esg_dashboard.scss",
        ]
    },
    "application": True,
    "installable": True,
    "license": "LGPL-3",
}
